;Configuración del Entorno
[Usuario]
ProyectoActual=
winX=100
winY=100
formX=100
formY=100
MostrarFavoritos=0

[App]
Nombre=Entorno básico
Descripcion=Organizador de Mis Proyectos de Trabajo
Autor=No especificado
Version=0.1

[Gui]
AnchoVentana=300
ColorFondo=White
ColorTexto=Black
FuenteNombre=Arial
FuenteTamano=9
Transparencia=255
MargenSup=10
MargenInf=10
MargenIzq=10
AnchoListaProy=202
AnchoTabsFavoritos=262
AltoFavorito=25
AnchoBotonBarra=24
AltoBotonBarra=24
PosListaProy=70
PosOpcionFavoritos=70

[Rutas]
EditorTxt=[ProgramFiles]\Notepad++\notepad++.exe
ArchivoLogs=[AppDir]\logs\[Entorno]_[Proyecto].log
DefComandos=[AppDir]\entornos\[Entorno]\comandos.txt
DefMenus=[AppDir]\entornos\[Entorno]\menus.txt
DefProyectos=[AppDir]\datos\[Entorno]_proyectos.txt
DefBotones=[AppDir]\entornos\[Entorno]\botones.txt
DefFavoritos=[AppDir]\entornos\[Entorno]\favoritos.txt
ImgDir=[AppDir]\img
Logo=[AppDir]\img\logo.png
MisProyectos=[MisDoc]

[Comandos]
ConsolaTitulo=Consola Gestor-CLI
AnchoForm=360
AnchoCampo=200
AnchoEtiq=120
DirTrabajo=[MisProyectos]\[Proyecto]\phpsinergia
CamposArchivo=
CamposGuardar=

[ExtArchivosCampos]

[DirArchivosCampos]

[OpcionesCampos]

[Proyecto]
