;--------------------------------
; CONSTANTES DE IDIOMA - ESPAÑOL

!define TXT_DescripcionArchivo "Instalador de ${NAME} para Windows"
!define TXT_TituloLicencia "Acuerdo de Licencia"
!define TXT_SubtituloLicencia "Por favor revise los términos de la licencia antes de instalar el software."
!define TXT_InstruccionesLicencia "Si acepta todos los términos del acuerdo, seleccione ACEPTO para continuar.$\n$\nDebe aceptar el acuerdo para poder instalar ${NAME}."
!define TXT_InstruccionesComponentes "Marque los componentes que desee instalar y desmarque aquellos que no desee. Presione Instalar para comenzar el proceso (requiere conexión a Internet)."
!define TXT_EtiqEjecutarApp "Ejecutar ${NAME} ahora"
!define TXT_EtiqRevisarNotas "Revisar notas en ${README}"
!define TXT_BotonAcepto "ACEPTO"
!define TXT_VentanaActualizador "Actualización de ${NAME}"
!define TXT_VentanaInstalador "Instalación de ${NAME}"
!define TXT_TituloWelcomeActualizador "Asistente para Actualizar$\n${NAME} v$VERSION"
!define TXT_InstruccionesWelcomeActualizador "Este programa ACTUALIZARÁ el software ${NAME} que está instalado en:$\n$\n$INSTDRIVE$0$\n$\nPodrá agregar nuevos componentes o restaurar los existentes, sin perder sus configuraciones y datos.$\n$\n$\nPresione Siguiente para continuar."
!define TXT_TituloFinishActualizador "Finalizando el Asistente para$\nActualizar ${NAME}"
!define TXT_InstruccionesFinishActualizador "${NAME} ha sido actualizado en:$\n$\n$INSTDRIVE$0$\n$\nPresione Terminar para cerrar este asistente."
!define TXT_TituloWelcomeInstalador "Asistente para Instalar$\n${NAME} v$VERSION"
!define TXT_InstruccionesWelcomeInstalador "Este programa INSTALARÁ el software ${NAME} en su computadora.$\n$\nSe recomienda que cierre todas las demás aplicaciones antes de iniciar la instalación. Esto hará posible actualizar archivos relacionados con el sistema sin tener que reiniciar el equipo.$\n$\n$\nPresione Siguiente para continuar."
!define TXT_TituloFinishInstalador "Finalizando el Asistente para$\nInstalar ${NAME}"
!define TXT_InstruccionesFinishInstalador "${NAME} ha sido instalado en su computadora.$\n$\nPresione Terminar para cerrar este asistente."
!define TXT_TituloInstFinalizada "Instalación completada"
!define TXT_SubtituloInstCompletada "Se ha completado el proceso de instalación de ${NAME}."
!define TXT_TituloInstCancelada "Instalación cancelada"
!define TXT_SubtituloInstCancelada "La instalación fue cancelada por el usuario."
!define TXT_TituloPrereq "Comprobación de Pre-requisitos"
!define TXT_SubtituloPrereq "Debe tener instalados PHP y Composer en su computadora local."
!define TXT_EtiqNomostrarDenuevo "No volver a mostrar esta página"
!define TXT_TituloComponentes "Opciones de instalación"
!define TXT_SubtituloComponentes "Indique los datos necesarios para descargar y copiar los componentes."
!define TXT_GbLibres "GB libres"
!define TXT_MsgFaltaDominio "Debe indicar el Dominio del Servidor"
!define TXT_MsgFaltanCredencialesFtp "Debe indicar Usuario y Contraseña FTP"
!define TXT_MsgFaltaProtocolo "Seleccione un Protocolo (HTTP o FTP) para realizar la prueba."
!define TXT_MsgConexionHttpExito "Conexión HTTP exitosa"
!define TXT_MsgConexionHttpError "Falló la conexión HTTP a $SERVER:"
!define TXT_MsgConexionFtpExito "Conexión FTP exitosa"
!define TXT_MsgConexionFtpError "Falló la conexión FTP a $SERVER:"
!define TXT_MsgDetallesRespuesta "Respuesta recibida:"
!define TXT_MsgExeNoEncontrado "No se encontró el programa ${APPFILE}.$\nEjecute nuevamente el instalador."
!define TXT_MsgUniNoEncontrado "No se encontró el desinstalador en:"
!define TXT_EtiqRutaInstalacion "Ruta de instalación"
!define TXT_EtiqUnidadDestino "Unidad de destino:"
!define TXT_EtiqConfigDescargas "Configuración de descargas"
!define TXT_EtiqProtocolo "Protocolo:"
!define TXT_EtiqDominioServidor "Dominio del servidor:"
!define TXT_EtiqUsuarioFtp "Usuario FTP:"
!define TXT_EtiqPassFtp "Contraseña FTP:"
!define TXT_BotonDesinstalar "Desinstalar"
!define TXT_BotonComprobar "Comprobar"
!define TXT_EtiqRecordarCreds "Recordar credenciales (FTP)"
!define TXT_EtiqDesinstalarHerramientas "¿Desea Desinstalar también las Herramientas externas (Requisitos y Complementos)?"
!define TXT_EtiqRemoverTodas "Remover todas"
!define TXT_MsgErrorDescargaFtp "No se pudo descargar por FTP"
!define TXT_MsgErrorDescargaHttp "No se pudo descargar por HTTP"
!define TXT_MsgErrorDescomprimir "Error al descomprimir"
!define TXT_CodigoRespuesta "Código de respuesta:"
!define TXT_MsgErrorTamano "Tamaño incorrecto de "
!define TXT_MsgDescargando "Descargar:"
!define TXT_MsgVerificando "Validar Hash SHA256:"
!define TXT_MsgInstalandoHerramienta "Instalar herramienta:"
!define TXT_EtiqReinstalar "(Reinstalar)"
!define TXT_SecPrograma "Programa"
!define TXT_GrpRequisitos "Requisitos"
!define TXT_GrpComplementos "Complementos"
!define TXT_GrpExtensiones "Extensiones"
!define TXT_GrpRecursos "Recursos"
!define TXT_MsgCalculandoEspacio "Calcular el espacio utilizado..."
!define TXT_MsgErrorHashNoCalculado "No se pudo obtener el Hash del archivo:"
!define TXT_MsgErrorHashNoCoincide "No coincide el Hash del archivo:"
!define TXT_LogSecPrograma "INSTALANDO ARCHIVOS DEL PROGRAMA"
!define TXT_LogSecConfig "CONFIGURANDO LA APLICACIÓN"
!define TXT_LogTitulo "INSTALACION DE ${NAME}"
!define TXT_EtiqVerRegistro "Ver Registro de Instalación"
!define TXT_MsgHashValidado "Hash validado:"
!define TXT_LogFechaHora "Fecha / Hora:"
!define TXT_LogVersion "Versión actual:"
!define TXT_LogServidorDescargas "Servidor de descargas:"
!define TXT_LogProtocoloTransfer "Protocolo de transferencia:"
!define TXT_LogAddPath "Agregar al Entorno Path:"
!define TXT_LogCreateShortCut "Crear Accesos directos en Escritorio y Menú Inicio"
!define TXT_LogWriteReg "Escribiendo Registro:"
!define TXT_LogDescargandoActualizacion "Descargar Actualizacion:"
!define TXT_LogInstalandoActualizacion "Instalar Actualizacion:"
!define TXT_MsgErrorActualizacion "Error al descargar la actualización"
!define TXT_MsgConfirmaDesinstalacion "¿Desea desinstalar la versión actualmente instalada?"
!define TXT_MsgConfirmaActualizacion "¿Confirma que desea actualizar ${NAME}, con las siguientes versiones...?"
!define TXT_MsgActualizacionCancelada "Actualización cancelada por el usuario"
!define TXT_MsgActual "Actual"
!define TXT_MsgNueva "Nueva"
