; txt_spanish.nsh
;================================
; MODULO: TEXTOS DE INTERFAZ
; IDIOMA: SPANISH - ESPAÑOL
;================================

;--------------------------------
LangString TXT_VentanaActualizador ${LANG_SPANISH} "Actualizar ${NAME}"
LangString TXT_TituloWelcomeActualizador ${LANG_SPANISH} "Asistente para Actualizar$\n${NAME} v$Version"
LangString TXT_InstruccionesWelcomeActualizador ${LANG_SPANISH} "Este programa actualizará el software ${NAME} que está instalado en:$\n$\n$InstDrive$INSTDIR$\n$\nPodrá agregar nuevos componentes o restaurar los existentes, sin perder sus configuraciones y datos.$\n$\n$\nPresione Siguiente para continuar."
LangString TXT_TituloFinishActualizador ${LANG_SPANISH} "Finalizando el Asistente para$\nActualizar ${NAME}"
LangString TXT_InstruccionesFinishActualizador ${LANG_SPANISH} "${NAME} ha sido actualizado en:$\n$\n$InstDrive$INSTDIR$\n$\nPresione Terminar para cerrar este asistente."
;--------------------------------
LangString TXT_VentanaInstalador ${LANG_SPANISH} "Instalar ${NAME}"
LangString TXT_TituloWelcomeInstalador ${LANG_SPANISH} "Asistente para Instalar$\n${NAME} v$Version"
LangString TXT_InstruccionesWelcomeInstalador ${LANG_SPANISH} "Este programa instalará el software ${NAME} en su computadora.$\n$\nSe recomienda que cierre todas las demás aplicaciones antes de iniciar la instalación. Esto hará posible actualizar archivos relacionados con el sistema sin tener que reiniciar el equipo.$\n$\n$\nPresione Siguiente para continuar."
LangString TXT_TituloFinishInstalador ${LANG_SPANISH} "Finalizando el Asistente para$\nInstalar ${NAME}"
LangString TXT_InstruccionesFinishInstalador ${LANG_SPANISH} "${NAME} ha sido instalado en su computadora.$\n$\nPresione Terminar para cerrar este asistente."
;--------------------------------
LangString TXT_MsgFaltaDominio ${LANG_SPANISH} "Debe indicar el Dominio del Servidor"
LangString TXT_MsgFaltanCredencialesFtp ${LANG_SPANISH} "Debe indicar Usuario y Contraseña"
LangString TXT_MsgFaltaProtocolo ${LANG_SPANISH} "Seleccione un Protocolo para realizar la prueba."
LangString TXT_MsgConexionExito ${LANG_SPANISH} "Conexión exitosa a $Server"
LangString TXT_MsgConexionError ${LANG_SPANISH} "Falló la conexión a $Server"
LangString TXT_MsgDetallesRespuesta ${LANG_SPANISH} "Respuesta recibida"
LangString TXT_MsgExeNoEncontrado ${LANG_SPANISH} "No se encontró el programa ${APPFILE}.$\nEjecute nuevamente el instalador."
LangString TXT_MsgUniNoEncontrado ${LANG_SPANISH} "No se encontró el desinstalador en"
LangString TXT_MsgErrorDescarga ${LANG_SPANISH} "No se pudo descargar el componente"
LangString TXT_MsgErrorDescomprimir ${LANG_SPANISH} "Error al descomprimir"
LangString TXT_MsgErrorTamano ${LANG_SPANISH} "Tamaño incorrecto"
LangString TXT_MsgDescargando ${LANG_SPANISH} "Descargando"
LangString TXT_MsgVerificando ${LANG_SPANISH} "Validando Hash SHA256"
LangString TXT_MsgCalculandoEspacio ${LANG_SPANISH} "Calculando el espacio utilizado..."
LangString TXT_MsgErrorHashNoCalculado ${LANG_SPANISH} "No se pudo obtener el Hash del archivo"
LangString TXT_MsgErrorHashNoCoincide ${LANG_SPANISH} "No coincide el Hash del archivo"
LangString TXT_MsgInstalando ${LANG_SPANISH} "Instalando"
LangString TXT_MsgHashValidado ${LANG_SPANISH} "Hash validado"
LangString TXT_MsgConfirmaDesinstalacion ${LANG_SPANISH} "¿Desea desinstalar la versión actualmente instalada?"
LangString TXT_MsgActualizacionCancelada ${LANG_SPANISH} "Actualización cancelada por el usuario"
;--------------------------------
LangString TXT_EtiqEjecutarApp ${LANG_SPANISH} "Ejecutar ${NAME} ahora"
LangString TXT_EtiqRevisarNotas ${LANG_SPANISH} "Revisar notas en ${READMEFILE}"
LangString TXT_EtiqNomostrarDenuevo ${LANG_SPANISH} "No volver a mostrar esta página"
LangString TXT_EtiqRutaInstalacion ${LANG_SPANISH} "Ruta de instalación"
LangString TXT_EtiqUnidadDestino ${LANG_SPANISH} "Unidad de destino"
LangString TXT_EtiqConfigDescargas ${LANG_SPANISH} "Configuración de descargas"
LangString TXT_EtiqProtocolo ${LANG_SPANISH} "Protocolo"
LangString TXT_EtiqDominioServidor ${LANG_SPANISH} "Dominio del servidor"
LangString TXT_EtiqUsuarioFtp ${LANG_SPANISH} "Usuario"
LangString TXT_EtiqPassFtp ${LANG_SPANISH} "Contraseña"
LangString TXT_EtiqRecordarCreds ${LANG_SPANISH} "Recordar credenciales"
LangString TXT_EtiqDesinstalarHerramientas ${LANG_SPANISH} "¿Desea Desinstalar también las Herramientas externas?"
LangString TXT_EtiqRemoverTodas ${LANG_SPANISH} "Remover todas"
LangString TXT_EtiqReinstalar ${LANG_SPANISH} "(Reinstalar)"
LangString TXT_EtiqVerRegistro ${LANG_SPANISH} "Ver Registro de Instalación"
;--------------------------------
LangString TXT_BotonDesinstalar ${LANG_SPANISH} "Desinstalar"
LangString TXT_BotonComprobar ${LANG_SPANISH} "Comprobar"
;--------------------------------
LangString TXT_LogSecPrograma ${LANG_SPANISH} "INSTALACION DEL PROGRAMA"
LangString TXT_LogSecConfig ${LANG_SPANISH} "CONFIGURACION DE LA APLICACIÓN"
LangString TXT_LogSection ${LANG_SPANISH} "INSTALACION DE "
LangString TXT_LogFechaHora ${LANG_SPANISH} "Fecha / Hora"
LangString TXT_LogVersion ${LANG_SPANISH} "Versión actual"
LangString TXT_LogServidorDescargas ${LANG_SPANISH} "Servidor de descargas"
LangString TXT_LogProtocoloTransfer ${LANG_SPANISH} "Protocolo de transferencia"
LangString TXT_LogAddPath ${LANG_SPANISH} "Agregando al Entorno Path"
LangString TXT_LogCreateShortCut ${LANG_SPANISH} "Creando Accesos directos en Escritorio y Menú Inicio"
LangString TXT_LogWriteReg ${LANG_SPANISH} "Escribiendo el Registro de Windows"
LangString TXT_LogGuardado ${LANG_SPANISH} "Archivo de registro de instalación en"
LangString TXT_LogNoGuardado ${LANG_SPANISH} "No se pudo guardar el archivo de registro de Instalación"
;--------------------------------
LangString TXT_TituloInstFinalizada ${LANG_SPANISH} "Instalación completada"
LangString TXT_SubtituloInstCompletada ${LANG_SPANISH} "Se ha completado el proceso de instalación de ${NAME}."
LangString TXT_TituloInstCancelada ${LANG_SPANISH} "Instalación cancelada"
LangString TXT_SubtituloInstCancelada ${LANG_SPANISH} "La instalación fue cancelada por el usuario."
LangString TXT_TituloPrereq ${LANG_SPANISH} "Comprobación de Pre-requisitos"
LangString TXT_SubtituloPrereq ${LANG_SPANISH} "Debe instalar además los siguientes programas en su computadora local."
LangString TXT_TituloComponentes ${LANG_SPANISH} "Opciones de instalación"
LangString TXT_SubtituloComponentes ${LANG_SPANISH} "Indique los datos necesarios para descargar y copiar los componentes."
LangString TXT_InstruccionesComponentes ${LANG_SPANISH} "Marque los componentes que desee instalar y desmarque aquellos que no desee. Presione Instalar para comenzar el proceso (requiere conexión a Internet)."
LangString TXT_GbLibres ${LANG_SPANISH} "GB libres"
LangString TXT_CodigoRespuesta ${LANG_SPANISH} "Código"
