; txt_spanish.nsh
;================================
; MODULO: TEXTOS DE INTERFAZ
; IDIOMA: SPANISH - ESPAÑOL
;================================

;--------------------------------
LangString TXT_VentanaActualizador ${LANG_SPANISH} "Actualizar ${NAME}"
LangString TXT_TituloWelcomeActualizador ${LANG_SPANISH} "Asistente para Actualizar$\n${NAME} v$Version"
LangString TXT_InstruccionesWelcomeActualizador ${LANG_SPANISH} "Este programa actualizará el software ${NAME} que está instalado en:$\n$\n$InstDrive$INSTDIR$\n$\nPodrá agregar nuevos componentes o restaurar los existentes, sin perder sus configuraciones y datos.$\n$\n$\nPresione Siguiente para continuar."
LangString TXT_TituloFinishActualizador ${LANG_SPANISH} "Finalizando el Asistente para$\nActualizar ${NAME}"
LangString TXT_InstruccionesFinishActualizador ${LANG_SPANISH} "${NAME} ha sido actualizado en:$\n$\n$InstDrive$INSTDIR$\n$\nPresione FINALIZAR para cerrar este asistente."
;--------------------------------
LangString TXT_VentanaInstalador ${LANG_SPANISH} "Instalar ${NAME}"
LangString TXT_TituloWelcomeInstalador ${LANG_SPANISH} "Asistente para Instalar$\n${NAME} v$Version"
LangString TXT_InstruccionesWelcomeInstalador ${LANG_SPANISH} "Este programa instalará el software ${NAME} en su computadora.$\n$\nSe recomienda que cierre todas las demás aplicaciones antes de iniciar la instalación. Esto hará posible actualizar archivos relacionados con el sistema sin tener que reiniciar el equipo.$\n$\n$\nPresione Siguiente para continuar."
LangString TXT_TituloFinishInstalador ${LANG_SPANISH} "Finalizando el Asistente para$\nInstalar ${NAME}"
LangString TXT_InstruccionesFinishInstalador ${LANG_SPANISH} "${NAME} ha sido instalado en su computadora.$\n$\nPresione FINALIZAR para cerrar este asistente."
;--------------------------------
LangString TXT_MsgFaltaDominio ${LANG_SPANISH} "Debe indicar el Dominio del Servidor"
LangString TXT_MsgFaltanCredenciales ${LANG_SPANISH} "Debe indicar Usuario y Contraseña"
LangString TXT_MsgFaltaProtocolo ${LANG_SPANISH} "Seleccione un Protocolo para realizar la prueba."
LangString TXT_MsgConexionExito ${LANG_SPANISH} "Conexión exitosa a $Server"
LangString TXT_MsgConexionError ${LANG_SPANISH} "Falló la conexión a $Server"
LangString TXT_MsgDetallesRespuesta ${LANG_SPANISH} "Respuesta recibida"
LangString TXT_MsgExeNoEncontrado ${LANG_SPANISH} "No se encontró el programa ${APPFILE}.$\nEjecute nuevamente el instalador."
LangString TXT_MsgUninstallNoEncontrado ${LANG_SPANISH} "No se encontró el desinstalador en"
LangString TXT_MsgErrorDescarga ${LANG_SPANISH} "No se pudo descargar el componente"
LangString TXT_MsgErrorCatalogo ${LANG_SPANISH} "No se pudo descargar el Catálogo de componentes desde $Server.$\nVuelva atrás a cambiar la $\"Configuración de descargas$\" en $\"Opciones de instalación$\"."
LangString TXT_MsgErrorDescomprimir ${LANG_SPANISH} "Error al descomprimir"
LangString TXT_MsgErrorTamano ${LANG_SPANISH} "Tamaño incorrecto"
LangString TXT_MsgDescargando ${LANG_SPANISH} "Descargando"
LangString TXT_MsgVerificando ${LANG_SPANISH} "Validando Hash SHA256"
LangString TXT_MsgCalculandoEspacio ${LANG_SPANISH} "Calculando el espacio utilizado..."
LangString TXT_MsgHashNoCalculado ${LANG_SPANISH} "No se pudo obtener el Hash del archivo"
LangString TXT_MsgHashNoCoincide ${LANG_SPANISH} "No coincide el Hash del archivo"
LangString TXT_MsgInstalando ${LANG_SPANISH} "Instalando"
LangString TXT_MsgHashValidado ${LANG_SPANISH} "Hash validado"
LangString TXT_MsgConfirmaDesinstalacion ${LANG_SPANISH} "¿Desea desinstalar la versión actualmente instalada?"
LangString TXT_MsgActualizacionCancelada ${LANG_SPANISH} "Actualización cancelada por el usuario"
;--------------------------------
LangString TXT_EtiqEjecutarApp ${LANG_SPANISH} "Ejecutar ${NAME} ahora"
LangString TXT_EtiqRevisarNotas ${LANG_SPANISH} "Revisar notas en ${READMEFILE}"
LangString TXT_EtiqNomostrarDenuevo ${LANG_SPANISH} "No volver a mostrar esta página"
LangString TXT_EtiqDiscoInstalacion ${LANG_SPANISH} "Dónde se instalará el Programa"
LangString TXT_EtiqRutaInstalacion ${LANG_SPANISH} "Ruta de instalación"
LangString TXT_EtiqUnidadDestino ${LANG_SPANISH} "Unidad de destino"
LangString TXT_EtiqConfigDescargas ${LANG_SPANISH} "Dónde buscar Componentes para descargar"
LangString TXT_EtiqProtocolo ${LANG_SPANISH} "Protocolo"
LangString TXT_EtiqDominioServidor ${LANG_SPANISH} "Dominio del servidor"
LangString TXT_EtiqUsuario ${LANG_SPANISH} "Usuario"
LangString TXT_EtiqPass ${LANG_SPANISH} "Contraseña"
LangString TXT_EtiqRecordarCreds ${LANG_SPANISH} "Recordar credenciales"
;LangString TXT_EtiqDesinstalarComponentes ${LANG_SPANISH} "¿Desea Desinstalar también los Componentes externos?"
;LangString TXT_EtiqRemoverTools ${LANG_SPANISH} "Remover Herramientas"
;LangString TXT_EtiqRemoverVendor ${LANG_SPANISH} "Remover PhpSinergIA"
;LangString TXT_EtiqRemoverResources ${LANG_SPANISH} "Remover Recursos"
LangString TXT_EtiqReinstalar ${LANG_SPANISH} "(Reinstalar)"
LangString TXT_EtiqVerRegistro ${LANG_SPANISH} "Ver Registro de Instalación"
LangString TXT_EtiqNoDetectado ${LANG_SPANISH} "No Detectado"
LangString TXT_EtiqDescargarDeSitioOficial ${LANG_SPANISH} "Descargar desde Sitio oficial"
LangString TXT_EtiqUbicacion ${LANG_SPANISH} "Ubicación de ${NAME}"
LangString TXT_EtiqRutaFinal ${LANG_SPANISH} "El programa se instalará en:   "
LangString TXT_EtiqAccesosDirectos ${LANG_SPANISH} "Crear Accesos Directos"
LangString TXT_EtiqMenuInicio ${LANG_SPANISH} "Grupo $\"${NAME}$\" en el Menú Inicio"
LangString TXT_EtiqEscritorioPrograma ${LANG_SPANISH} "Enlace a ${NAME} en el Escritorio"
LangString TXT_EtiqEscritorioActualizador ${LANG_SPANISH} "Enlace al Actualizador (este Asistente)"
LangString TXT_EtiqInicioWindows ${LANG_SPANISH} "Configuración de inicio"
LangString TXT_EtiqEjecutarInicio ${LANG_SPANISH} "Ejecutar ${NAME} al iniciar Windows"
;--------------------------------
LangString TXT_BotonDesinstalar ${LANG_SPANISH} "Desinstalar"
LangString TXT_BotonComprobar ${LANG_SPANISH} "Comprobar"
LangString TXT_BotonAcepto ${LANG_SPANISH} "ACEPTO"
LangString TXT_BotonFinalizar ${LANG_SPANISH} "FINALIZAR"
;--------------------------------
LangString TXT_LogSecBase ${LANG_SPANISH} "INSTALACION DEL PROGRAMA"
LangString TXT_LogSecConfig ${LANG_SPANISH} "CONFIGURACION DE LA APLICACIÓN"
LangString TXT_LogSection ${LANG_SPANISH} "INSTALACION DE "
LangString TXT_LogFechaHora ${LANG_SPANISH} "Fecha / Hora"
LangString TXT_LogVersion ${LANG_SPANISH} "Versión actual"
LangString TXT_LogServidorDescargas ${LANG_SPANISH} "Servidor de descargas"
LangString TXT_LogProtocoloTransfer ${LANG_SPANISH} "Protocolo de transferencia"
LangString TXT_LogAddPath ${LANG_SPANISH} "Agregando al Entorno Path"
LangString TXT_LogPostInstall ${LANG_SPANISH} "Configurando elementos Post-instalación"
LangString TXT_LogWriteReg ${LANG_SPANISH} "Escribiendo el Registro de Windows"
LangString TXT_LogGuardado ${LANG_SPANISH} "Archivo de registro de instalación en"
LangString TXT_LogNoGuardado ${LANG_SPANISH} "No se pudo guardar el archivo de registro de Instalación"
;--------------------------------
LangString TXT_TituloInstFinalizada ${LANG_SPANISH} "Instalación completada"
LangString TXT_SubtituloInstCompletada ${LANG_SPANISH} "Se ha completado el proceso de instalación de ${NAME}."
LangString TXT_TituloInstCancelada ${LANG_SPANISH} "Instalación cancelada"
LangString TXT_SubtituloInstCancelada ${LANG_SPANISH} "La instalación fue cancelada por el usuario."
LangString TXT_TituloPrereq ${LANG_SPANISH} "Comprobación de Pre-requisitos"
LangString TXT_SubtituloPrereq ${LANG_SPANISH} "Las funciones avanzadas de ${NAME} requieren que tenga los siguientes programas en su computadora."
LangString TXT_TituloConfirm ${LANG_SPANISH} "Post-Instalación"
LangString TXT_SubtituloConfirm ${LANG_SPANISH} "Confirme los elementos que desea añadir una vez finalizada la instalación."
LangString TXT_TituloComponentes ${LANG_SPANISH} "Opciones para Instalación"
LangString TXT_SubtituloComponentes ${LANG_SPANISH} "Indique los datos necesarios para descargar y copiar los componentes."
LangString TXT_InstruccionesComponentes ${LANG_SPANISH} "Marque los componentes que desee instalar y desmarque aquellos que no desee. Presione Instalar para comenzar el proceso (requiere conexión a Internet)."
LangString TXT_SeleccionarComponentes ${LANG_SPANISH} "Seleccione los componentes:"
LangString TXT_GbLibres ${LANG_SPANISH} "GB libres"
LangString TXT_CodigoRespuesta ${LANG_SPANISH} "Código"
LangString TXT_TituloLicencia ${LANG_SPANISH} "Acuerdo de licencia"
LangString TXT_SubtituloLicencia ${LANG_SPANISH} "Por favor, revise los términos de la licencia antes de instalar este software."
LangString TXT_InstruccionesLicenciaSup ${LANG_SPANISH} "Presione Avanzar Página para ver el resto del acuerdo."
LangString TXT_InstruccionesLicenciaInf ${LANG_SPANISH} "Si acepta todos los términos del acuerdo, presione el botón ACEPTO para continuar.$\nDebe aceptar el acuerdo para instalar ${NAME}."
LangString TXT_InstruccionesDesinstalar ${LANG_SPANISH} "${NAME} se desinstalará del siguiente directorio. Presione Siguiente para continuar."
LangString TXT_UbicacionDesinstalar ${LANG_SPANISH} "Ubicación"
